include:
  project: gitlab-classrooms/autograding
  file: maven-junit.yml

variables:
  CC_APP_ID: app_6d6406a2-7a4e-49de-80a3-e8b0190e3d7b
deploy:
  image:
    name: clevercloud/clever-tools:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - clever link -a $CC_APP_ID
    - clever deploy --force
